version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/dev/Dockerfile
    command: bun index.js
    volumes:
      - .:/workspace
    depends_on:
      - mongo
    environment:
      TOKEN_BOT: ${CERAIA_BOT_TOKEN_DISCORD}
      MONGO_URI: mongodb://${CERAIA_MONGODB_USERNAME}:${CERAIA_MONGODB_PASSWORD}@ceraia-mongo:27017/<BOT>?authSource=admin
    labels:
      traefik.enable: "false"
    networks:
      - ceraia-bot

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CERAIA_MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${CERAIA_MONGODB_PASSWORD}
    volumes:
      - ./data/mongo-db:/app/backend/data
      - ./data/mongo-configdb:/app/backend/data
    networks:
      - ceraia-bot
  
  express:
    image: mongo-express:latest
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${CERAIA_MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${CERAIA_MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${CERAIA_MONGODB_USERNAME}:${CERAIA_MONGODB_PASSWORD}@ceraia-mongo:27017/
    networks:
      - ceraia-bot

volumes:
  mongodb-data: