version: "3"

services:
  bot:
    image: ghcr.io/axodouble/xdbl-bot:main
    restart: unless-stopped
    command: node index.js
    environment:
      TOKEN: DISCORDTOKEN
      MONGOURI: mongodb://root:changethisibegofu@mongo:27017/discord?authSource=admin
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changethisibegofu
  mongo-express: # Optional, only for web interface and exploring the database
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: changethisibegofu
      ME_CONFIG_MONGODB_URL: mongodb://root:changethisibegofu@mongo:27017/