version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TOKEN: DISCORDTOKEN
      MONGOURI: MONGOURI
    command: node index.js
    restart: unless-stopped