name: Create Release on Commit

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit hash
        id: get_commit_hash
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_commit_hash.outputs.hash }}
          release_name: Release ${{ steps.get_commit_hash.outputs.hash }}
          draft: false
          prerelease: false
