name: Create Release on Commit

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{git rev-parse --short HEAD}}
          release_name: Release ${{git rev-parse --short HEAD}}
          draft: false
          prerelease: false
